# Triangle in NumPy Arrays

Auxiliary notebook to the my blog post at [carlosevmoura.org](https://carlosevmoura.org/2021/02/triangles-in-numpy-arrays/).

## Importing NumPy Library

In [1]:
import numpy as np

In [10]:
my_matrix = np.arange(16).reshape(4, 4)
my_matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## Obtaining the diagonal and diagonal size of this matrix

In [11]:
my_matrix.diagonal()

array([ 0,  5, 10, 15])

In [5]:
my_matrix.diagonal().size

4

## Obtaining indexes for the triangles using *np.tril_indices*
We applied "k=-1" to exclude the diagonal of the matrix in the triangle indices.

In [12]:
tril_my_matrix = np.tril_indices(my_matrix.diagonal().size, k=-1)
tril_my_matrix

(array([1, 2, 2, 3, 3, 3]), array([0, 0, 1, 0, 1, 2]))

## Using the indices in the matrix
### Indices for the lower triangle

In [13]:
my_matrix[tril_my_matrix[0], tril_my_matrix[1]]

array([ 4,  8,  9, 12, 13, 14])

### Indices for the upper triangle

In [16]:
my_matrix[tril_my_matrix[1], tril_my_matrix[0]]

array([ 1,  2,  6,  3,  7, 11])

## Unpacking the triangles to create new matrices

In [18]:
zero_matrix = np.zeros((4, 4))
zero_matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
lower_triangle = zero_matrix.copy()
lower_triangle[tril_my_matrix[0], tril_my_matrix[1]] = my_matrix[tril_my_matrix[0], tril_my_matrix[1]].copy()
lower_triangle

array([[ 0.,  0.,  0.,  0.],
       [ 4.,  0.,  0.,  0.],
       [ 8.,  9.,  0.,  0.],
       [12., 13., 14.,  0.]])

In [21]:
upper_triangle = zero_matrix.copy()
upper_triangle[tril_my_matrix[1], tril_my_matrix[0]] = my_matrix[tril_my_matrix[1], tril_my_matrix[0]].copy()
upper_triangle

array([[ 0.,  1.,  2.,  3.],
       [ 0.,  0.,  6.,  7.],
       [ 0.,  0.,  0., 11.],
       [ 0.,  0.,  0.,  0.]])

## Thank you! :D